first_conv_filters: 12
first_conv_kernel: (7, 7)
first_conv_stride: (2, 2)
base_strides: [(2, 2), (1, 1), (1, 1), (2, 2)]
base_channels: [16, 22, 26, 32]
base_layers: [1, 1, 2, 1]
base_t_expansions: [1, 6, 6, 6]
base_kernel_size: [[(3, 3), (5, 5), (3, 3), (3, 3)]
classifier_filters: 40